// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYD8dj0SmsK9Bqfi8Ru5YeDTkwblLG7ys',
    appId: '1:522524650443:web:90fe9bf5635122549b244e',
    messagingSenderId: '522524650443',
    projectId: 'vivamais-7d836',
    authDomain: 'vivamais-7d836.firebaseapp.com',
    storageBucket: 'vivamais-7d836.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa2dCbxjaK0lLib5Y1r-6ZdjQbVGxIkhc',
    appId: '1:522524650443:android:f932096a6cbc052b9b244e',
    messagingSenderId: '522524650443',
    projectId: 'vivamais-7d836',
    storageBucket: 'vivamais-7d836.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcZnAUFEan3ETzo2hbFAFWcY656Hl6yC4',
    appId: '1:522524650443:ios:772397ee3ca984b09b244e',
    messagingSenderId: '522524650443',
    projectId: 'vivamais-7d836',
    storageBucket: 'vivamais-7d836.firebasestorage.app',
    iosBundleId: 'com.example.dispositivosMoveisGp0029vno07a',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcZnAUFEan3ETzo2hbFAFWcY656Hl6yC4',
    appId: '1:522524650443:ios:772397ee3ca984b09b244e',
    messagingSenderId: '522524650443',
    projectId: 'vivamais-7d836',
    storageBucket: 'vivamais-7d836.firebasestorage.app',
    iosBundleId: 'com.example.dispositivosMoveisGp0029vno07a',
  );
}
